[book]
title = "GB ASM Tutorial"
description = "A complete guide to programming Game Boy games in assembly."
language = "en"
src = "src"

[build]
create-missing = true             # This is kept for convenience, but CI sets it to false
use-default-preprocessors = false
extra-watch-dirs = ["po"]

[preprocessor.links]

[preprocessor.gettext]
command = "cargo run -p i18n-helpers --bin mdbook-gettext --locked --release --"
before = ["links"]

# Custom preprocessor for our custom markup
[preprocessor.custom]
command = "cargo run -p preproc --locked -rq --"

# Custom back-end for our custom markup
[output.custom]
command = "cargo run -p renderer --locked -rq --"

[output.html]
additional-css = ["css/custom.css"]
additional-js = ["js/linenos.js"]
smart-punctuation = true
print = { enable = true }
fold = { enable = true, level = 0 }
git-repository-url = "https://github.com/gbdev/gb-asm-tutorial"
edit-url-template = "https://github.com/gbdev/gb-asm-tutorial/edit/master/{path}"
site-url = "/gb-asm-tutorial/"

[output.linkcheck]
optional = true
